language: ruby
sudo: required
dist: trusty
group: stable

matrix:
  include:
    - rvm: 1.9.3
    - rvm: 2.0.0
    - rvm: 2.1.10
    - rvm: 2.2.5
    - rvm: 2.3.1
    - rvm: ruby-head
    - rvm: jruby-9.1.5.0
      env: JRUBY_OPTS="--dev -J-Djruby.launch.inproc=true -J-Xmx1024M"
    - rvm: jruby-1.7.26
      env: JRUBY_OPTS="--dev -J-Djruby.launch.inproc=true -J-Xmx1024M"
    - rvm: rubinius-3
  allow_failures:
    - rvm: jruby-1.7.26
    - rvm: jruby-9.1.5.0
    - rvm: rubinius-3
