% require "common_prelude.rb"

resources:
<%= erbify_file "common_resources.yml" -%>
  - name: loofah-pr
    type: pull-request
    icon: "github-circle"
    source:
      repo: flavorjones/loofah
      access_token: ((github-repo-status-access-token))
      ignore_paths: <%= $common_ignore_paths %>

resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

jobs:
  - name: pr-pending
    public: true
    plan:
      - get: loofah-pr
        trigger: true
        version: every
      - put: loofah-pr
        params:
          path: loofah-pr
          status: pending

  - name: pr-success
    public: true
    disable_manual_trigger: true
    plan:
      - get: loofah-pr
        trigger: true
        version: every
        passed:
% RUBIES[:mri].each do |ruby_version|
          - ruby-<%= ruby_version %>-pr
% end
      - put: loofah-pr
        params:
          path: loofah-pr
          status: success

% RUBIES[:mri].each do |ruby_version|
  - name: ruby-<%= ruby_version %>-pr
    public: true
    serial_groups: ["ruby-pr"]
    plan:
      - get: ci
      - get: loofah-pr
        trigger: true
        version: every
        passed: [pr-pending]
      - task: rake-test
        config:
          image_resource:
            type: docker-image
            source: {repository: ruby, tag: "<%= ruby_version %>"}
          platform: linux
          inputs:
            - name: ci
            - name: loofah-pr
              path: loofah
          params:
            NOKOGIRI_USE_SYSTEM_LIBRARIES: t
          run:
            path: ci/concourse/tasks/rake-test/run.sh
        on_failure:
          put: loofah-pr
          params:
            path: loofah-pr
            status: failure
% end
