% require "common_prelude.rb"

resource_types:
- name: pull-request
  type: registry-image
  source:
    repository: teliaoss/github-pr-resource

resources:
<%= erbify_file "common_resources.yml" -%>
  - name: loofah-pr
    type: pull-request
    icon: github
    check_every: 15m
    # https://ci.nokogiri.org/api/v1/teams/nokogiri-core/pipelines/loofah-pr/resources/loofah-pr/check/webhook?webhook_token=((webhook_token))
    webhook_token: ((loofah-pr-webhook-token))
    source:
      repository: flavorjones/loofah
      access_token: ((github-repo-status-access-token))
      ignore_paths: <%= $common_ignore_paths %>

jobs:
  - name: pr-pending
    public: true
    plan:
      - get: loofah-pr
        trigger: true
        version: every
      - put: loofah-pr
        params:
          path: loofah-pr
          status: PENDING

  - name: pr-success
    public: true
    disable_manual_trigger: true
    plan:
      - get: loofah-pr
        trigger: true
        version: every
        passed:
% RUBIES[:mri].each do |ruby_version|
          - ruby-<%= ruby_version %>-pr
% end
      - put: loofah-pr
        params:
          path: loofah-pr
          status: SUCCESS

% RUBIES[:mri].each do |ruby_version|
  - name: ruby-<%= ruby_version %>-pr
    public: true
    plan:
      - get: ci
      - get: loofah-pr
        trigger: true
        version: every
        passed: [pr-pending]
      - task: rake-test
        config:
          image_resource:
            type: registry-image
            source: {repository: ruby, tag: "<%= ruby_version %>"}
          platform: linux
          inputs:
            - name: ci
            - name: loofah-pr
              path: loofah
          params:
            NOKOGIRI_USE_SYSTEM_LIBRARIES: t
          run:
            path: ci/concourse/tasks/rake-test/run.sh
        on_failure:
          put: loofah-pr
          params:
            path: loofah-pr
            status: FAILURE
% end
